elasticsearch:
  host: 124.223.158.87
  # es服务端口
  #124.223.158.87
  port: 9200
  rest:
    uris: http://124.223.158.87:9200
#    本地账户密码
#    username: elastic
#    password: 123456

#    服务器账户密码
    username: es
    password: Zh09101026

spring:
  servlet:
    multipart:
      max-file-size: 2GB
      max-request-size: 2GB

  boot:
    run:
      jvmArguments: -Xmx1g

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver

    url: jdbc:mysql://127.0.0.1:3306/policy?useUnicode=true&useSSL=false&characterEncoding=utf8&nullCatalogMeansCurrent=true
    username: root
    password: 72efb2c6f255b629
#    password: Zh09101026

# Sa-Token配置
sa-token:
  # token 名称 (同时也是cookie名称)
  token-name: satoken
  # token 有效期，单位s 默认30天, -1代表永不过期
  timeout: 2592000
  # token 临时有效期 (指定时间内无操作就视为token过期) 单位: 秒
  activity-timeout: -1
  # 是否允许同一账号并发登录 (为true时允许一起登录, 为false时新登录挤掉旧登录)
  is-concurrent: true
  # 在多人登录同一账号时，是否共用一个token (为true时所有登录共用一个token, 为false时每次登录新建一个token)
  is-share: false
  # token风格
  token-style: uuid
  # 是否输出操作日志
  is-log: false
